withingsslack/logger.py, withingsslack/main.py
Add a logging package which creates a context correlation id.
Add a middleware which sets this correlation id to a new uuid on each new request.
Provide configuration for uvicorn logs:
* Add timestamps to default logs
* Add timestamps and correlation id to access logs
=> Add logging middleware to include correlation id in logging and response headers

tests/data/fitbit_sleep_response_classic.json, tests/services/fitbit/test_parser.py, withingsslack/services/fitbit/parser.py
Support parsing the following two formats of fitbit sleep data to calculate awake vs sleep time:
Classic:
```json
{                       
"sleep": [          
{           
"levels": {
"summary": {
"asleep": {
"minutes": 439
},
"awake": {
"minutes": 2
}
}
},
"type": "classic"
}
]
}
```
stages:
```json
{
"sleep": [
{
"duration": 11040000,
"levels": {
"summary": {
"wake": {
"minutes": 28
}
}
},
"type": "stages"
}
]
}
```
=> Support parsing fitbit classic data

withingsslack/main.py
Perhaps we're getting logged out due to withings double webhook calls: if the access token is expired, we may have been trying to refresh the token twice.
=> Prevent multiple concurrent requests to refresh a withings access token

requirements/dev.txt, requirements/prod.txt, slackhealthbot/logger.py, slackhealthbot/main.py, slackhealthbot/services/fitbit/oauth.py, slackhealthbot/services/fitbit/requests.py, slackhealthbot/services/slack.py, slackhealthbot/services/withings/oauth.py, slackhealthbot/services/withings/requests.py, slackhealthbot/services/withings/signing.py, tests/routes/test_withings_routes.py, tests/test_fitbit_poll.py
This is a first step toward migrating toward async apis.
=> Async Step 1 - Replace requests lib with httpx lib

requirements/prod.txt, slackhealthbot/database/connection.py, slackhealthbot/database/crud.py, slackhealthbot/database/models.py, slackhealthbot/logger.py, slackhealthbot/main.py, slackhealthbot/scheduler.py, slackhealthbot/services/fitbit/api.py, slackhealthbot/services/fitbit/oauth.py, slackhealthbot/services/fitbit/requests.py, slackhealthbot/services/fitbit/service.py, slackhealthbot/services/withings/api.py, slackhealthbot/services/withings/oauth.py, slackhealthbot/services/withings/requests.py, tests/conftest.py, tests/routes/test_withings_routes.py, tests/test_factories.py, tests/test_fitbit_poll.py
* Use sqlalchemy async apis for accessing the database
* For tests:
- Continue to use `mocked_session`, a synchronous session, for factory-boy (which doesn't yet support async apis)
- Use an `AsyncSession` for the rest of tests where we call our app code.
=> Async Step 3 - Use the db in async mode

slackhealthbot/main.py, tests/fixtures/fitbit_scenarios.py, tests/routes/test_fitbit_routes.py, tests/routes/test_withings_routes.py, tests/test_fitbit_poll.py
---
Fix naming and comments in test_withings_routes:
The test `test_first_user_weight` initially only tested a scenario where no previous weight was logged. It was modified after to test different scenarios. Updating the test name and inline comments to reflect that.
---
Extract test scenarios out of test_fitbit_poll into fitbit_scenarios.
---
Add a test for the fitbit notification webhook.
It currently fails because we don't correctly save the sleep data.
---
Fix bug where sleep data wasn't saved when the fitbit notification webhook was called.
=> Various fixes to incoming webhooks for withings/fitbit notifications

slackhealthbot/services/fitbit/parser.py, tests/fixtures/fitbit_scenarios.py, tests/routes/test_fitbit_routes.py, tests/test_fitbit_poll.py
Add tests for invalid json responses returned by fitbit for retrieving sleep and activities.
Handle errors parsing fitbit responses for sleep and activities.
=> Handle invalid responses returned by fitbit for retrieving sleep and activities

slackhealthbot/main.py
Don't handle a notification for a user if we already got one within the last 10 seconds.
Rename `last_processed_notification_per_user` to `last_processed_withings_notification_per_user`, since we now have to do this for both withings and fitbit.
=> Prevent handling duplicate fitbit notifications

slackhealthbot/services/fitbit/parser.py, slackhealthbot/services/fitbit/service.py, slackhealthbot/services/models.py, slackhealthbot/services/slack.py, tests/fixtures/fitbit_scenarios.py, tests/routes/test_fitbit_routes.py
* Define an enum for the activity zone, instead of using the zoneName from the fitbit api directly.
This will help us to refer to specific column names of the future activities table, like `cardio_minutes` or `fat_burn_minutes`.
* Remove some assertions from unit tests that are redundant with factory tests.
=> Refactoring preparation to show progress of fitbit activities

slackhealthbot/services/slack.py, tests/routes/test_fitbit_routes.py
Add unit test to reproduce bug where slack message contains "None".
Adapt the slack service to avoid this bug: use an empty string if we can't find the icon.
=> Fix issue where slack message for an activity may contain "None".

slackhealthbot/services/fitbit/parser.py
We sometimes receive a fitbit sleep webhook notification, but the message isn't posted to slack. Log some details to help troubleshoot.
=> Add logs to debug fitbit sleep notifications.

slackhealthbot/main.py
For both withings and fitbit: mark a notification as processed only if we successfully fetched data.
Sometimes when we fetch data, it's not ready yet. Example fetch response after receiving a sleep notification:
```json
{
"meta": {
"retryDuration":3000,
"state":"pending"
},
"sleep":[],
"summary": {
"totalMinutesAsleep":0,
"totalSleepRecords":0,
"totalTimeInBed":0
}
}
```
It contains no sleep data.
A duplicate notification was received a few seconds after this one, but we ignored it. Maybe we should have tried the fetch.
=> Change duplicate webhook notification behavior.

slackhealthbot/services/fitbit/service.py, slackhealthbot/services/withings/requests.py, tests/routes/test_fitbit_routes.py, tests/routes/test_withings_routes.py
* Create unit tests to test refreshing the oauth token after receiving a fitbit or withings notification webhook.
* Fix bugs found by the new tests.
=> Test oauth token refresh and fix related bugs

slackhealthbot/main.py, slackhealthbot/scheduler.py, slackhealthbot/services/fitbit/api.py, slackhealthbot/services/fitbit/oauth.py, slackhealthbot/services/fitbit/requests.py, slackhealthbot/services/fitbit/service.py, tests/routes/test_fitbit_routes.py
Add compliance hooks for fitbit behavior which deviates from default behavior expected by authlib.
Regarding refreshing the token:
* Remove our custom decorator which was refreshing the token upon a 401 error to a resource request.
* When we get/refresh our access token, save it in the db with an expiration date which is a few minutes sooner than the real one. This will help ensure that we'll fetch a new token when we want to do a resource request and our token is about to expire.
=> Fitbit: Integrate authlib instead of doing oauth manually

ruff.toml, scripts/codecheck.sh, slackhealthbot/database/crud.py, slackhealthbot/main.py, slackhealthbot/services/fitbit/oauth.py, slackhealthbot/services/slack.py, slackhealthbot/services/withings/oauth.py, tests/conftest.py, tests/routes/test_fitbit_routes.py, tests/routes/test_withings_routes.py, tests/test_fitbit_poll.py
* Apply PL (pylint) checks with ruff, and format errors in github format.
* Fix PLR2004 issues regarding magic numbers.
* Fix PLR0913 issues regarding functions with too many arguments.
* Fix PLR0913 issues regarding functions with too many arguments, in tests.
=> Apply PL (pylint) checks with ruff, and format errors in github format.

slackhealthbot/main.py
Fix this warning:
slackhealthbot/main.py:56: DeprecationWarning:
on_event is deprecated, use lifespan event handlers instead.
Read more about it in the
[FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
Use lifespan instead of `on_event`.
=> Fix DeprecationWarning from FastAPI.

slackhealthbot/tasks/fitbitpoll.py, tests/tasks/test_fitbit_oauth.py
Add tests for certain oauth flows during fitbit polling:
* successful token refresh
* token refresh fail
* user logged out
These tests are a bit of copy/paste from other tests:
* routes/test_fitbit_oauth: we copy most of the test scenario, except the part about receiving the webhook about new fitbit data
* tasks/test_fitbit_poll: we copy just the part about polling for activity (instead of the using the webhook).
In the first commit, the tests fail, because of a missing `await` on a coroutine call in the polling code. 
The second commit fixes this.
=> Add tests for oauth flows during fitbit polling (and fix bug about missing `await`).

slackhealthbot/data/repositories/fitbitrepository.py, slackhealthbot/domain/modelmappers/remoteservicetodomain/activity.py, slackhealthbot/domain/modelmappers/repositorytodomain/activity.py, slackhealthbot/domain/usecases/fitbit/usecase_get_last_activity.py, slackhealthbot/domain/usecases/fitbit/usecase_process_new_activity.py, slackhealthbot/domain/usecases/fitbit/usecase_process_new_sleep.py, slackhealthbot/domain/usecases/slack/usecase_post_sleep.py, slackhealthbot/oauth/fitbitconfig.py, slackhealthbot/oauth/withingsconfig.py, slackhealthbot/remoteservices/fitbit/activityapi.py, slackhealthbot/remoteservices/fitbit/sleepapi.py, slackhealthbot/routers/dependencies.py, tests/domain/modelmappers/remoteservicetodomain/test_remote_service_sleep_to_domain_sleep.py
* Fix some type hints
* Suppress warning about acessing `_asdict()` in sqlalchemy. It's [documented](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Row._asdict).
* Avoid using `input` as a variable/argument name, as it's a built-in symbol.
* Define a method as `@staticmethod` if it doesn't need to access any class or instance fields.
* ~Add missing `await` before a call of an async function.~ Fixed in #61
* Convert str explicitly to `ActivityZone` enum instances, where enum instances are expected.
=> Fix various pycharm warnings.

tests/conftest.py, tests/data/repositories/test_fitbitrepository.py, tests/domain/modelmappers/remoteservicetodomain/test_remote_service_sleep_to_domain_sleep.py, tests/domain/usecases/slack/test_usecase_post_activity.py, tests/domain/usecases/slack/test_usecase_post_sleep.py, tests/routes/test_fitbit_oauth.py, tests/routes/test_fitbit_routes.py, tests/routes/test_withings_oauth.py, tests/routes/test_withings_routes.py, tests/tasks/test_fitbit_oauth.py, tests/tasks/test_fitbit_poll.py, tests/test_factories.py, tests/testsupport/fixtures/fitbit_scenarios.py
* Don't use `input` as a variable/argument name, as it's a builtin symbol
* Fix some type hints
* Fix some unused arguments (when required to be present, prefix the arguments with underscore).
* Fix some grammar errors
* Use `xyz_factory.create()` instead of `xyz_factory()`.
- See https://github.com/FactoryBoy/factory_boy/issues/468
- PIDD: Pycharm inspection driven development 🤷
* Fix lines which are too long
* Fix regex pattern to match literal parentheses
* Suppress a pycharm warning about accessing the _meta field of a factory boy factory instance. The field is documented.
=> Fix some more pycharm warnings (in test code).

slackhealthbot/core/exceptions.py, slackhealthbot/data/repositories/sqlalchemyfitbitrepository.py, slackhealthbot/data/repositories/sqlalchemywithingsrepository.py, slackhealthbot/routers/fitbit.py, slackhealthbot/routers/withings.py, tests/routes/test_fitbit_routes.py, tests/routes/test_withings_routes.py
Instead of returning a 500 and logging a traceback to the console: return a 404.
=> Handle webhook notifications for unknown users

slackhealthbot/domain/usecases/slack/usecase_post_activity.py, tests/testsupport/fixtures/fitbit_scenarios.py
* If we don't have a previous activity of the same type with a distance:
- don't put "None" for the trend icon. Just leave it as an empty space.
- do display an "all time record" text.
* Display 3 digits after the decimal place.
* Add a space between the number and the "km" unit.
=> Issue #72: fix a few bugs with activity distance in km

config/app-default.yaml, slackhealthbot/containers.py, slackhealthbot/domain/usecases/fitbit/usecase_process_new_activity.py, slackhealthbot/domain/usecases/slack/usecase_post_activity.py, slackhealthbot/domain/usecases/slack/usecase_post_daily_activity.py, slackhealthbot/main.py, slackhealthbot/settings.py, tests/domain/usecases/fitbit/test_usecase_process_daily_activities.py, tests/domain/usecases/slack/test_usecase_post_activity.py, tests/tasks/test_post_daily_activities.py, tests/testsupport/config/app-test.yaml, tests/testsupport/testdata/fitbit_scenarios.py
Issue #83 
Adapt the reporting settings in the app yaml config.
Before:
```yaml
report_daily: true
report_realtime: false
```
Now:
```yaml
report:
daily: true
realtime: false
fields:
- distance
- calories
- # ... etc
```
Add a `default_report` block as a child of `activities`.
Add a `report` block as a child of an item of `activity_types`.
The config for an activity type can override the settings in the `default_report` block.
Only the fields listed in the `fields` attribute will be included in the message posted to Slack.
=> Issue #83 - Step 3 - Configure which fields should be reported to slack, per activity.

slackhealthbot/domain/usecases/fitbit/usecase_process_new_activity.py, tests/testsupport/testdata/fitbit_scenarios.py
* Create a test to reproduce the bug.
* Fix the bug by falling back to the default report configuration.
=> Fix a config bug with activity_type item not containing a `report` block.

config/app-default.yaml, slackhealthbot/domain/usecases/slack/usecase_post_daily_activity.py, slackhealthbot/settings.py, tests/domain/usecases/fitbit/test_usecase_process_daily_activities.py
Add an optional `daily_goals` block for the `report` configuration of an activity type.
Currently this block has only one supported attribute: `distance_km`, whose value is a float.
When posting a daily report to slack, indicate if the day's distance total has exceeded the daily `distance_km` goal for that activity type.
=> Add daily goals.

scripts/codecheck.sh, scripts/run_tests.sh, slackhealthbot/data/database/models.py, slackhealthbot/data/repositories/sqlalchemyfitbitrepository.py, slackhealthbot/domain/localrepository/localfitbitrepository.py, slackhealthbot/domain/models/activity.py, slackhealthbot/domain/usecases/fitbit/usecase_process_daily_activity.py, slackhealthbot/domain/usecases/slack/usecase_post_daily_activity.py, tests/data/repositories/test_fitbitrepository.py, tests/domain/usecases/fitbit/test_usecase_process_daily_activities.py, tests/tasks/test_post_daily_activities.py, tests/testsupport/fixtures/db.py
* CI script improvements:
* Make scripts executable.
* Enable logging of SQL queries when running tests.
* Pass `run_tests.sh` arguments to pytest.     
To see SQL queries when running tests: `./scripts/run_tests -sv`
* Correct the type hint for the `date` field in the `FitbitDailyActivity` view.
Implement streak reporting.
For this iteration, streaks are only reported for distance.
If a goal is set for distance, the streak is the last X days, including today, where the distance goal was met.
If no goal was set for distance, the streak is the last X days, including today, where there was activity.
The streak information is included as part of the "distance" item in the Slack message.
This is an MVP. The code will surely need to be refactored, if/when we decide to calculate streaks wrt …
=> Implement streak reporting

slackhealthbot/containers.py, slackhealthbot/domain/usecases/fitbit/usecase_calculate_streak.py, slackhealthbot/domain/usecases/fitbit/usecase_process_daily_activity.py, tests/domain/usecases/fitbit/test_usecase_process_daily_activities.py
* Adjust a unit test to reproduce the bug.
* Fix the bug:
- First, move the streak calculation to its own use case, as it's getting to be a bit big.
- Then: if we didn't meet the goal today, don't even bother trying to calculate the streak. We know it's 0.
=> Fix streak calculation when we didn't meet the goal today.

config/app-default.yaml, slackhealthbot/oauth/fitbitconfig.py, slackhealthbot/oauth/requests.py, slackhealthbot/oauth/withingsconfig.py, slackhealthbot/remoteservices/api/slack/messageapi.py, slackhealthbot/settings.py
This means the client will also have the configured timeouts and retries for:
* oauth requests (ex: token refresh)
* retrieving fitness data from withings and fitbit
* posting messages to slack
=> Configure http timeouts and retries globally on the httpx clients.

config/app-default.yaml, slackhealthbot/data/repositories/sqlalchemyfitbitrepository.py, slackhealthbot/domain/localrepository/localfitbitrepository.py, slackhealthbot/domain/usecases/fitbit/usecase_calculate_streak.py, slackhealthbot/settings.py, tests/domain/usecases/fitbit/test_usecase_process_daily_activities.py
Issue #90 
* comments: Adjust the comment/example for the current streak algorithm.
* refacto: Refactor activity streak calculation, keeping current streak calculation logic.
- Make the repository return the number of days in the streak, instead of the earliest date in the streak.
- The future streak calculation logic will evolve: it will ignore days with no activity at all. So returning an "earliest date in the streak" won't help to calculate the number days in the streak.
* Add a new app report configuation: `streak_mode`, with possible values:
- `strict`: same streak behavior as before.
- `lax`: days without any activity at all don't break the "streak".
The values are documented in `app-default.xml`.
* Implement the logic for the `lax` streak mode calculation:
- If a goal is set (with …
=> Update streak logic
